In [25]:
import numpy as np 

In [26]:
arr = np.random.randint(1, 100, size=(10, 5)) # sample = 10, feature = 5

In [27]:
arr.shape

(10, 5)

In [28]:
b = arr.reshape(5, 10)

b.shape
b.ndim
b

array([[29, 41,  6, 19, 89, 49, 83, 25, 25, 54],
       [87, 65, 11, 81, 33, 48, 93, 98, 95, 47],
       [39, 26, 74, 56, 86, 69, 65, 39,  1, 54],
       [72, 53, 52,  1, 10, 68, 79, 54, 31, 96],
       [ 2, 67, 69, 90, 57, 42, 42, 69,  5, 88]], dtype=int32)

In [29]:
flatten = b.flatten()
print(flatten.ndim)
flatten


folumn_wise_flattening = np.ravel(b, order = 'F')
print(folumn_wise_flattening)

1
[29 87 39 72  2 41 65 26 53 67  6 11 74 52 69 19 81 56  1 90 89 33 86 10
 57 49 48 69 68 42 83 93 65 79 42 25 98 39 54 69 25 95  1 31  5 54 47 54
 96 88]


In [30]:
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

print(a, b)

[[7 6 9]
 [5 7 7]] [[22 28 21]
 [22 21 23]]


# concatenate

In [31]:
com_row = np.concatenate((a, b), axis=0 ) # row wise

print(com_row)

con_col = np.concatenate((a, b), axis=1)   # column wise
print(con_col)

[[ 7  6  9]
 [ 5  7  7]
 [22 28 21]
 [22 21 23]]
[[ 7  6  9 22 28 21]
 [ 5  7  7 22 21 23]]


In [32]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1, 10, size=(2, 3))
y = np.random.randint(1, 10, size=(1, 3))

r = np.concatenate((x, y), axis=0)
print(r)

[[7 3 6]
 [4 3 3]
 [6 9 4]]


In [33]:
# transpose

mat = np.array([[10, 20, 30],
                [30, 40, 50]
               ])

transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [41]:
# array split

a = np.random.randint(1, 10, size=(10, ))
print(a)

splitted_array = np.array_split(a,3)
print(splitted_array)

# split -> equal division
splitted_array = np.plit(a,3)

[3 2 3 4 1 3 4 2 5 5]
[array([3, 2, 3, 4], dtype=int32), array([1, 3, 4], dtype=int32), array([2, 5, 5], dtype=int32)]


AttributeError: module 'numpy' has no attribute 'plit'

## Arithmetic operator and Mathematical functions

In [47]:
# faster for vectorization

x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

add = x+y
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

reminder = x%y
print(reminder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [52]:
# mathematical function

# trigonometry

# sin, cos, tan takes values in radian
sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad
rad_con = np.deg2rad(x)
print(rad_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [54]:
# log

x = np.array([10, 20, 30, 40])

base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt = 

[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]
