In [1]:
import numpy as np 

In [2]:
arr = np.random.randint(1, 100, size=(10, 5)) # sample = 10, feature = 5

In [3]:
arr.shape

(10, 5)

In [4]:
b = arr.reshape(5, 10)

b.shape
b.ndim
b

array([[19,  3, 73, 83, 72, 24,  5, 83, 67, 30],
       [44, 97, 29, 91, 83, 40, 90, 94, 70, 56],
       [14, 80, 95, 90, 95, 99, 31, 69, 26, 13],
       [90, 93, 27, 91, 33, 31, 69, 22, 11, 73],
       [97, 17, 98,  6, 56, 15, 22, 47, 30, 39]], dtype=int32)

In [5]:
flatten = b.flatten()
print(flatten.ndim)
flatten


folumn_wise_flattening = np.ravel(b, order = 'F')
print(folumn_wise_flattening)

1
[19 44 14 90 97  3 97 80 93 17 73 29 95 27 98 83 91 90 91  6 72 83 95 33
 56 24 40 99 31 15  5 90 31 69 22 83 94 69 22 47 67 70 26 11 30 30 56 13
 73 39]


In [6]:
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

print(a, b)

[[8 1 8]
 [4 9 3]] [[29 29 27]
 [27 24 20]]


# concatenate

In [7]:
com_row = np.concatenate((a, b), axis=0 ) # row wise

print(com_row)

con_col = np.concatenate((a, b), axis=1)   # column wise
print(con_col)

[[ 8  1  8]
 [ 4  9  3]
 [29 29 27]
 [27 24 20]]
[[ 8  1  8 29 29 27]
 [ 4  9  3 27 24 20]]


In [8]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1, 10, size=(2, 3))
y = np.random.randint(1, 10, size=(1, 3))

r = np.concatenate((x, y), axis=0)
print(r)

[[8 9 8]
 [8 5 8]
 [8 7 2]]


In [9]:
# transpose

mat = np.array([[10, 20, 30],
                [30, 40, 50]
               ])

transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [10]:
# array split

a = np.random.randint(1, 10, size=(10, ))
print(a)

splitted_array = np.array_split(a,3)
print(splitted_array)

# split -> equal division
splitted_array = np.plit(a,3)

[2 3 8 8 2 7 6 4 5 8]
[array([2, 3, 8, 8], dtype=int32), array([2, 7, 6], dtype=int32), array([4, 5, 8], dtype=int32)]


AttributeError: module 'numpy' has no attribute 'plit'

## Arithmetic operator and Mathematical functions

In [11]:
# faster for vectorization

x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

add = x+y
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

reminder = x%y
print(reminder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [12]:
# mathematical function

# trigonometry

# sin, cos, tan takes values in radian
sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad
rad_con = np.deg2rad(x)
print(rad_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[0.17453293 0.34906585 0.52359878 0.6981317 ]


In [15]:
# log

x = np.array([10, 20, 30, 40])

base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt = np.sqrt(x)
print(sqrt)

[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]
[3.16227766 4.47213595 5.47722558 6.32455532]


In [19]:
# different
s = np.sum(x)
print(s)

cumul = np.cumulative_sum(x)
print(cumul)

100
[ 10  30  60 100]


# Logical Function

In [24]:
# comparison ->,<, >=, <=, ==, !=


x = np.array([10, 8, 16, 100 ]) 
y = np.array([2, 3, 4, 5])

greather_than = x>y
print(greather_than)

equal = x==y
print(equal)


# all () -> shob true kina
# any () -> jeno ekta true ase kina 

print(np.all(greather_than))
print(np.any(equal))

[ True  True  True  True]
[False False False False]
True
False


# Sorting

In [25]:
# inplace

x = np.array([10, 8, 16, 100])

z = x.copy()
print(z)
z.sort()
print(z)



[ 10   8  16 100]
[  8  10  16 100]


In [27]:
# copy sorting

print(x)
sort_arr = np.sort(x)

print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [29]:
# 2d array sorting

mat = np.array([[10, 3, 5], [8, 4, 9]])

# horizon axis = 1

hor_sort = np.sort(mat, axis=1)
print(hor_sort)

vert_sort = np.sort(mat, axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# Searching

In [30]:
print(x)

[ 10   8  16 100]


In [36]:
# np.where(condition), x, y if true x, otherwise replace with y

index = np.where(x==8)     # returns index
print(index)

index = np.where(x>8, x,0)      # return array
print(index)

(array([1]),)
[ 10   0  16 100]


In [37]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [41]:
index = np.where(mat>8)     # returns index
print(index)

arr = np.where(mat>8, mat,0)      # return array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [47]:
x = np.array([10, 100, 8, 16, 100])


maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


# counting in ndarray

In [48]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[54 17  8  2 48 91 71 34 50 43 49 62 95 81 78 77 17 68 62 72 43 97 49 18
 45 59 70 58 65 17 20 32 97 86 47 75 53 79 24 48 73  6 92 81 61 37 97  4
 19 98 20 29 26 52 60 51 90 75 88 50 55 13 20 70 64 99 12 73  2 52 61 14
 72 69 44 53 43 24 35 55 60 89 30 61  7 92 47 11 84 91 97 87 13 42  8 30
  1 98 24 15]


In [49]:
value_great_then_60 = np.count_nonzero(a==97)
print(value_great_then_60)

4


In [52]:
unique_value, count = np.unique(a, return_counts=True)

print(unique_value)
print(count)

[ 1  2  4  6  7  8 11 12 13 14 15 17 18 19 20 24 26 29 30 32 34 35 37 42
 43 44 45 47 48 49 50 51 52 53 54 55 58 59 60 61 62 64 65 68 69 70 71 72
 73 75 77 78 79 81 84 86 87 88 89 90 91 92 95 97 98 99]
[1 2 1 1 1 2 1 1 2 1 1 3 1 1 3 3 1 1 2 1 1 1 1 1 3 1 1 2 2 2 2 1 2 2 1 2 1
 1 2 3 2 1 1 1 1 2 1 2 2 2 1 1 1 2 1 1 1 1 1 1 2 2 1 4 2 1]


# Statistical function

In [53]:
# data load

data = np.genfromtxt('student_scores.csv', delimiter = ', ', skip_hearder = 1)
print(data)

TypeError: genfromtxt() got an unexpected keyword argument 'skip_hearder'. Did you mean 'skip_header'?

In [56]:
# statistics
math_marks = data[::, :1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation

std_math_marks = np.std(math_marks)
print(std_math_marks)

NameError: name 'data' is not defined

In [57]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


# Linear algebra

In [58]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)

# trace
print(np.trace(B))

[[ 58  64]
 [139 154]]
17


In [59]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

0.0
2


In [60]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
