In [4]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)

PyTorch version: 2.11.0+cpu
CUDA available: False
CUDA version: None


In [7]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device name {torch.cuda.get_device_name(0)}")

else:
    print("GPU is not available")

GPU is not available


In [8]:
a = torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
type(a)

torch.Tensor

In [10]:
a = torch.zeros(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
a = torch.ones(2, 3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
a = torch.rand(2, 3)
a

tensor([[0.9035, 0.2170, 0.9125],
        [0.5904, 0.4528, 0.9711]])

In [13]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.tensor( [ [1,2,3], [4,5,6] ] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [17]:
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x, dtype= torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data Type

In [26]:
x.dtype

torch.int64

In [27]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype= torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [29]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype= torch.float32)

tensor([1., 2., 3., 4.])

In [30]:
x.dtype

torch.int64

In [31]:
x = x.to(torch.float32)

In [32]:
x.dtype

torch.float32

# Mathematical Operations

In [33]:
X = torch.tensor([ [1,2,3], [4, 5, 6] ])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
X + 2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [35]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
X - 2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [37]:
X * 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [38]:
X / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [41]:
# floor

X = X * 100

In [42]:
X // 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [43]:
X ** 2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [44]:
X % 2

tensor([[0, 0, 0],
        [0, 0, 0]])

# Element Wise Operation

In [45]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [46]:
b

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [47]:
a + b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [48]:
a - b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [49]:
a * b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [50]:
a / b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [51]:
a ** b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [52]:
a % b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [53]:
c = torch.tensor([-1, -2, -3, -4 ])

In [54]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [55]:
torch.neg(c)

tensor([1, 2, 3, 4])

In [56]:
d = torch.tensor( [1.2, 2.5, 3.5, 4.5])

In [57]:
torch.round(d)

tensor([1., 2., 4., 4.])

In [58]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [59]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [60]:
torch.clamp(d, min = 1, max= 2)

tensor([1.2000, 2.0000, 2.0000, 2.0000])

 # Reduction Operations

In [61]:
e = torch.randint(size=(2,3), low= 0, high = 10, dtype=torch.float32)

In [62]:
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [63]:
torch.sum(e)

tensor(27.)

In [65]:
torch.mean(e)

tensor(4.5000)

In [66]:
torch.sum(e, dim = 0)

tensor([9., 9., 9.])

In [67]:
torch.sum(e, dim = 1)

tensor([10., 17.])

In [68]:
torch.mean(e, dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [69]:
torch.mean(e, dim = 1)

tensor([3.3333, 5.6667])

In [70]:
torch.median(e)

tensor(1.)

In [71]:
torch.max(e)

tensor(9.)

In [72]:
torch.min(e)

tensor(0.)

In [73]:
torch.prod(e)

tensor(0.)

In [74]:
torch.std(e)

tensor(4.5935)

In [75]:
torch.var(e)

tensor(21.1000)

In [77]:
# argmin, argmax

torch.argmax(e)

tensor(2)

In [78]:
torch.argmin(e)

tensor(0)

# matrix opertions

In [83]:
f = torch.randint( size = (2,3), low=0, high = 10)
g = torch.randint( size = (3,2), low=0, high = 10)

In [84]:
f

tensor([[5, 9, 9],
        [7, 5, 9]])

In [85]:
g

tensor([[8, 9],
        [7, 9],
        [2, 6]])

In [86]:
torch.matmul(f, g)

tensor([[121, 180],
        [109, 162]])

In [89]:
# dot product

vector1 = torch.tensor( [1, 2] )
vector2 = torch.tensor( [3, 4] )

In [90]:
torch.dot(vector1, vector2)

tensor(11)

In [91]:
f.shape

torch.Size([2, 3])

In [92]:
torch.transpose(f, 0, 1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [95]:
h = torch.randint(size=(3, 3), low=0, high = 10, dtype = torch.float32)

In [96]:
torch.det(h)

tensor(-48.)

In [97]:
torch.inverse(h)

tensor([[ 0.0000,  0.5000, -0.3750],
        [ 0.3333, -1.0833,  0.6875],
        [ 0.0000, -0.2500,  0.3125]])

 # Comparision Operations

In [98]:
i = torch.randint( size = (2, 3), low = 0, high = 10)
j = torch.randint( size = (2, 3), low = 0, high = 10)

In [99]:
i

tensor([[4, 7, 2],
        [3, 8, 5]])

In [100]:
j

tensor([[6, 2, 9],
        [5, 0, 4]])

In [101]:
# greater than

i > j

tensor([[False,  True, False],
        [False,  True,  True]])

In [105]:
# less than

i < j

tensor([[ True, False,  True],
        [ True, False, False]])

In [103]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [104]:
i != j

tensor([[True, True, True],
        [True, True, True]])

 # Special Functions

In [114]:
k = torch.tensor( [0.001, 20, 30] )
k

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

In [108]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [109]:
# exponential

torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [110]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [111]:
# sigmoid

torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [115]:
# softmax

torch.softmax(k, dim = 0)

tensor([9.3666e-14, 4.5398e-05, 9.9995e-01])

In [116]:
torch.relu(k)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

# Inplace operations

In [117]:
a = torch.tensor( [1, 2, 3] )
a

tensor([1, 2, 3])

In [119]:
b = a + 5
b

tensor([6, 7, 8])

In [121]:
m = torch.rand( 2, 3 )
n = torch.rand( 2, 3 )

In [122]:
m

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [123]:
n

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [124]:
m.add_(n)

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [125]:
torch.relu_(m)

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

In [126]:
m.relu_()

tensor([[0.9638, 0.9448, 0.4670],
        [0.6286, 1.1429, 1.1066]])

# Copying a tensor

In [141]:
a = torch.tensor([1, 2, 3, 4, 5])
a

tensor([1, 2, 3, 4, 5])

In [134]:
b = a

In [135]:
b

tensor([1, 2, 3, 4, 5])

In [136]:
b[2] = 30

In [137]:
b

tensor([ 1,  2, 30,  4,  5])

In [138]:
a

tensor([ 1,  2, 30,  4,  5])

In [142]:
b = a.clone()

In [143]:
b

tensor([1, 2, 3, 4, 5])

In [144]:
id(a)

2191932656368