In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [ ]:
X.shape

(10, 2)

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
# Custom Dataset

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]



In [ ]:
dataset = CustomDataset(X, y)

In [ ]:
# len

len(dataset)

10

In [ ]:
dataset[2]

(array([-2.8953973 ,  1.97686236]), np.int64(0))

# DataLoader

In [14]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [15]:
for batch_feature, batch_label in dataloader:
  print(batch_feature)
  print(batch_label)

tensor([[-0.5872, -1.9717],
        [-1.9629, -0.9923]], dtype=torch.float64)
tensor([0, 0])
tensor([[-0.7206, -0.9606],
        [ 1.7273, -1.1858]], dtype=torch.float64)
tensor([0, 1])
tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1, 0])
tensor([[-0.9382, -0.5430],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([1, 0])
tensor([[1.8997, 0.8344],
        [1.7774, 1.5116]], dtype=torch.float64)
tensor([1, 1])
