In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.5


In [3]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [6]:
# 1D

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
# 2D

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(type(b))

print(b.ndim, b.shape, b.size)

<class 'numpy.ndarray'>
2 (2, 3) 6


In [12]:
print(b.dtype)

int64


In [14]:
c = np.array([1, 2, 4.5], dtype=np.int64)
print(c.dtype)
print(c)

int64
[1 2 4]


In [15]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
print(np.full((3, 4), 10))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [18]:
print(np.eye(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [19]:
print(np.empty((1, 2)))

[[1.29666639e-311 0.00000000e+000]]


In [20]:
print(np.random.randint(10, 20, (4, 4)))

[[11 12 14 16]
 [16 11 16 15]
 [17 11 18 19]
 [11 11 17 17]]


In [21]:
print(np.arange(0, 11, 5))

[ 0  5 10]


In [22]:
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
a = np.array([[10, 20, 30],
             [40, 50, 60,],
             [70, 80, 90]])

print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
print(a[0][1])

20


In [26]:
print(a[1][1])

50


In [28]:
a[0, :]

array([10, 20, 30])

In [29]:
a[0, 0:2]

array([10, 20])

In [30]:
a[:, 0]

array([10, 40, 70])

In [31]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [32]:
print(a[:, -1])

[30 60 90]


In [33]:
print(np.diag(a))

[10 50 90]


In [34]:
print(a[0:2, 0:2])

[[10 20]
 [40 50]]


In [35]:
a = np.array([10, 20, 30, 40, 50])

print(a[[0, 2, 4]])

[10 30 50]


In [36]:
print(a[a>40])

[50]


In [37]:
print(a[a%20==0])

[20 40]


In [40]:
a = np.array([10, 20, 30, 40, 50, 60])

print(a)
print(a.reshape(2,3))
print(a.reshape(3,2))

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]
[[10 20]
 [30 40]
 [50 60]]


In [42]:
print(a.reshape(3,2))
print(a.reshape(3,2).T)

[[10 20]
 [30 40]
 [50 60]]
[[10 30 50]
 [20 40 60]]


In [43]:
a = np.array([3, 7, 2, 9, 5])
print(a)

[3 7 2 9 5]


In [44]:
# all => AND
print(np.all(a>5))

False


In [46]:
# any => OR
print(np.any(a>5))
print(np.any(a>50))

True
False


In [47]:
a = np.array(['hello', 'world', 'numpy'])


In [53]:
print(np.char.upper(a))
print(np.char.capitalize(a))
print(np.char.add(a, "+"))
print(np.char.startswith(a, 'n'))
print(np.char.split("one two three four"))

['HELLO' 'WORLD' 'NUMPY']
['Hello' 'World' 'Numpy']
['hello+' 'world+' 'numpy+']
[False False  True]
['one', 'two', 'three', 'four']


In [56]:
a = np.array([0, np.pi/2, np.pi])

print(a)
print(np.sin(a))
print(np.cos(a))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [61]:
b = np.array([1, 4, 9, 19])

print(np.sqrt(b))
print(np.log(b))
print(np.log10(b))
print(np.exp(a))

[1.         2.         3.         4.35889894]
[0.         1.38629436 2.19722458 2.94443898]
[0.         0.60205999 0.95424251 1.2787536 ]
[ 1.          4.81047738 23.14069263]


In [66]:
a = np.array([[2, 4, 6], [1, 3, 5]])

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.percentile(a, 50))
print(np.var(a))

3.5
3.5
1.707825127659933
3.5
2.9166666666666665


In [68]:
result = np.mod(10, 3)
print(result)

1


In [70]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print(np.sort(a))
print(np.argsort(a))
print(np.argmax(a))
print(np.argmin(a))

[1 1 2 3 4 5 6 9]
[1 3 6 0 2 4 7 5]
5
1


In [71]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [72]:
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

In [73]:
d = np.dot(A, B)
print(d)

[[ 58  64]
 [139 154]]


In [74]:
print(np.linalg.inv(d))

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [75]:
print(np.linalg.matrix_transpose(d))

[[ 58 139]
 [ 64 154]]


# Array Creation and Manipulation
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0. [ Home work]

In [76]:
a = np.random.randint(1, 21, (5, 5))
print(a)

[[ 4 19 14 11  7]
 [11  3 19 19  9]
 [ 8  9 14 11 11]
 [18  1  4 12  5]
 [ 1 12  3 13 11]]


In [78]:
print(a[:, 2])
a[:, 2] = 1
print(a)

[14 19 14  4  3]
[[ 4 19  1 11  7]
 [11  3  1 19  9]
 [ 8  9  1 11 11]
 [18  1  1 12  5]
 [ 1 12  1 13 11]]


In [79]:
a = np.random.randint(1, 17, (4, 4))
print(a)

[[ 8  2 12 13]
 [ 8 14  4  2]
 [ 5  8 13 10]
 [14  6  2  5]]


In [80]:
np.fill_diagonal(a, 0)
print(a)

[[ 0  2 12 13]
 [ 8  0  4  2]
 [ 5  8  0 10]
 [14  6  2  0]]


# Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border. (HW)

In [81]:
a = np.random.randint(1, 36, (6, 6))
print(a)

[[34 15  7 22  9  7]
 [ 2 21 19 30 15 22]
 [20 20  9 14  5 29]
 [30  8 19 17 16 20]
 [10 12  3 19  3 30]
 [30 33 24 31 32  1]]


In [82]:
print(a[2:5, 1:4])

[[20  9 14]
 [ 8 19 17]
 [12  3 19]]


In [83]:
a = np.random.randint(1, 36, (6, 6))
b = np.random.randint(1, 36, (6, 6))

print(a[1], b[1])

[20  5 14 26 27  3] [22 19 11 17  3 26]


In [85]:
np.concatenate((a[1], b[1]))

array([20,  5, 14, 26, 27,  3, 22, 19, 11, 17,  3, 26], dtype=int32)

In [86]:
x = np.random.randint(1, 36, (5, 5))
print(x)

[[34  8 17  2 28]
 [ 8 20  9 23 18]
 [ 4 26  3 16 33]
 [33 25 31  1 18]
 [31  9  9 21 12]]


In [87]:
top = a[0, :]
bottom = a[-1, :]
left = a[1: -1, 0]
right = a[1: -1, -1]

border = np.concatenate((top, right, bottom[::-1], left[::-1]))
print(border)

[ 7  9 15 32  7 33  3 24 22 15  1 23 20  8 28 16 23 32 33 20]


# Array Operations
1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [90]:
a = np.random.randint(1, 36, (3, 4))
b = np.random.randint(1, 36, (3, 4))

print(a + b)
print(a - b)

[[30 28 18 45]
 [43 37 30 40]
 [18 26 50 19]]
[[ 18   2 -16  23]
 [-27 -19  22 -16]
 [  2   8  14 -15]]


In [91]:
a = np.random.randint(1, 3, (4, 4))
print(a)

[[2 2 2 1]
 [1 2 1 2]
 [2 1 2 1]
 [1 1 1 1]]


In [92]:
print(np.sum(a))

23


In [93]:
# row 
print(np.sum(a, axis=1))

[7 6 6 4]


In [94]:
# col
print(np.sum(a, axis=0))

[6 6 6 5]


# Statistical Operations
1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array. ( HW)

In [100]:
a = np.random.randint(1,4, (5, 5))
print(a)

print("Mean : ",np.mean(a))
print("Median : ", np.median(a))
print("Standard : ", np.std(a))
print("Variance : ", np.var(a))

[[2 3 3 2 3]
 [1 2 1 2 3]
 [2 2 2 2 2]
 [3 1 2 1 3]
 [1 2 3 2 2]]
Mean :  2.08
Median :  2.0
Standard :  0.6881860213634101
Variance :  0.4735999999999999


# Boolean Indexing
1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [101]:
a = np.random.randint(1, 30, (4,4))
print(a)

[[ 1  6 17 27]
 [19 26 28 29]
 [21  8 22  1]
 [ 7 25 16  4]]


In [102]:
a[a>10] = 10
print(a)

[[ 1  6 10 10]
 [10 10 10 10]
 [10  8 10  1]
 [ 7 10 10  4]]
