## Version 1

In [1]:
import torch
import torch.nn as nn

In [9]:
# class Model(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()

#     self.linear = nn.Linear(num_features, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features):
#     out = self.linear(features)
#     out = self.sigmoid(out)

#     return out

## Version 2

In [18]:
# class Model(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()

#     # layer 1

#     self.linear1 = nn.Linear(num_features, 3)
#     self.relu = nn.ReLU()

#     # layer 2
#     self.linear2 = nn.Linear(3, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features):
#     out = self.linear1(features)
#     out = self.relu(out)

#     out = self.linear2(out)
#     out = self.sigmoid(out)

#     return out

## Version 3

In [27]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),   # index 0
        nn.ReLU(),                    # index 1
        nn.Linear(3, 1),              # index 2
        nn.Sigmoid()                  # index 3
    )


  def forward(self, features):
    out = self.network(features)

    return out

In [28]:
# Create dataset

features = torch.rand(10, 5)

In [11]:
features

tensor([[0.6063, 0.4000, 0.5623, 0.0933, 0.3624],
        [0.5897, 0.0851, 0.3760, 0.2771, 0.5311],
        [0.0178, 0.4142, 0.9876, 0.7509, 0.2701],
        [0.2337, 0.9422, 0.9499, 0.2778, 0.7189],
        [0.7905, 0.5241, 0.1209, 0.9884, 0.3960],
        [0.3628, 0.9117, 0.6304, 0.9140, 0.3623],
        [0.2746, 0.6556, 0.6059, 0.9692, 0.8044],
        [0.1737, 0.3170, 0.9469, 0.3385, 0.4385],
        [0.0054, 0.7455, 0.6228, 0.5893, 0.9857],
        [0.3915, 0.3018, 0.6392, 0.9847, 0.1595]])

In [29]:
features.shape[1]

5

In [30]:
#create model

model = Model(features.shape[1])

In [31]:
# Calling model for forward pass
# model.forward(features)

model(features)


tensor([[0.5625],
        [0.5489],
        [0.5582],
        [0.5588],
        [0.5463],
        [0.5601],
        [0.5638],
        [0.5455],
        [0.5696],
        [0.5555]], grad_fn=<SigmoidBackward0>)

In [35]:
# Show model weights

model.network[0].weight

Parameter containing:
tensor([[-0.1279, -0.1242,  0.0253,  0.0168, -0.1518],
        [ 0.2094,  0.1508, -0.2781, -0.1416, -0.1935],
        [-0.0248, -0.4398,  0.3023, -0.4121,  0.4236]], requires_grad=True)

In [25]:
# Visualize

!pip install torchinfo

In [33]:
from torchinfo import summary

summary(model, input_size= (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00